### ISSUE TITLE
LibDS spuriously connects to roboRIO

### ISSUE THREAD

**Issue by calcmogul** [WinT-3794/LibDS#2]
I've been having issues recently getting QDriverStation to communicate with a roboRIO. When QDriverStation is opened, the communications light on the roboRIO turns green and stays that way until I close QDriverStation, while QDriverStation's `Communications` and `Robot Code` lights share the same color and alternate between red and green every second. I performed testing connected directly to the roboRIO via an ethernet cable. I am able to ping both the roboRIO's mDNS address and static IP address.

The official FRC Driver Station is able to connect to the roboRIO successfully via a bridged network connection from within a Windows virtual machine, and it is able to run robot code in Operator Control.

Since older WPILib releases and QDriverStation v16.06.2-stable exhibit the same behavior, I'm thinking the issue is related to upgrading to either Qt 5.6 or 5.7 (I don't remember testing 5.6). Since I run Arch Linux, I can't downgrade to test an earlier version of Qt. I wrote a simple console Driver Station using LibDS which cannot connect either (https://github.com/calcmogul/ConsoleDS). I haven't verified the same symptoms are manifesting yet, but I'm fairly certain the bug exists in LibDS and not QDriverStation.

After fixing the test compilation with #1, the tests for `Test_SocketsSenderTCP` fail. The following is the full test output for the current HEAD of master with hash 6435333:

```
[tav@myriad tests]$ ./LibDS_Test 
********* Start testing of Test_CRC32 *********
Config: Using QtTest library 5.7.0, Qt 5.7.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 6.1.1 20160602)
PASS   : Test_CRC32::initTestCase()
PASS   : Test_CRC32::cleanupTestCase()
Totals: 2 passed, 0 failed, 0 skipped, 0 blacklisted, 0ms
********* Finished testing of Test_CRC32 *********
********* Start testing of Test_Watchdog *********
Config: Using QtTest library 5.7.0, Qt 5.7.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 6.1.1 20160602)
PASS   : Test_Watchdog::initTestCase()
PASS   : Test_Watchdog::cleanupTestCase()
Totals: 2 passed, 0 failed, 0 skipped, 0 blacklisted, 0ms
********* Finished testing of Test_Watchdog *********
********* Start testing of Test_DS_Config *********
Config: Using QtTest library 5.7.0, Qt 5.7.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 6.1.1 20160602)
PASS   : Test_DS_Config::initTestCase()
PASS   : Test_DS_Config::cleanupTestCase()
Totals: 2 passed, 0 failed, 0 skipped, 0 blacklisted, 0ms
********* Finished testing of Test_DS_Config *********
********* Start testing of Test_DriverStation *********
Config: Using QtTest library 5.7.0, Qt 5.7.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 6.1.1 20160602)
PASS   : Test_DriverStation::initTestCase()
PASS   : Test_DriverStation::cleanupTestCase()
Totals: 2 passed, 0 failed, 0 skipped, 0 blacklisted, 0ms
********* Finished testing of Test_DriverStation *********
********* Start testing of Test_SocketsSenderUDP *********
Config: Using QtTest library 5.7.0, Qt 5.7.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 6.1.1 20160602)
PASS   : Test_SocketsSenderUDP::initTestCase()
PASS   : Test_SocketsSenderUDP::checkFMS()
PASS   : Test_SocketsSenderUDP::checkRadio()
PASS   : Test_SocketsSenderUDP::checkRobot()
PASS   : Test_SocketsSenderUDP::cleanupTestCase()
Totals: 5 passed, 0 failed, 0 skipped, 0 blacklisted, 103ms
********* Finished testing of Test_SocketsSenderUDP *********
********* Start testing of Test_SocketsSenderTCP *********
Config: Using QtTest library 5.7.0, Qt 5.7.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 6.1.1 20160602)
QDEBUG : Test_SocketsSenderTCP::initTestCase() FMS Address set to "0.0.0.0"
QDEBUG : Test_SocketsSenderTCP::initTestCase() Radio Address set to "0.0.0.0"
QDEBUG : Test_SocketsSenderTCP::initTestCase() Robot Address set to "0.0.0.0"
QWARN  : Test_SocketsSenderTCP::initTestCase() QIODevice::write (QTcpSocket): device not open
QWARN  : Test_SocketsSenderTCP::initTestCase() QIODevice::write (QTcpSocket): device not open
QWARN  : Test_SocketsSenderTCP::initTestCase() QIODevice::write (QTcpSocket): device not open
PASS   : Test_SocketsSenderTCP::initTestCase()
FAIL!  : Test_SocketsSenderTCP::checkFMS() Compared values are not the same
   Actual   (fmsData) : ""
   Expected (testData): "Hello World"
   Loc: [Test_Sockets.h(140)]
FAIL!  : Test_SocketsSenderTCP::checkRadio() Compared values are not the same
   Actual   (radData) : ""
   Expected (testData): "Hello World"
   Loc: [Test_Sockets.h(144)]
FAIL!  : Test_SocketsSenderTCP::checkRobot() Compared values are not the same
   Actual   (robData) : ""
   Expected (testData): "Hello World"
   Loc: [Test_Sockets.h(148)]
PASS   : Test_SocketsSenderTCP::cleanupTestCase()
Totals: 2 passed, 3 failed, 0 skipped, 0 blacklisted, 107ms
********* Finished testing of Test_SocketsSenderTCP *********
********* Start testing of Test_NetConsoleSender *********
Config: Using QtTest library 5.7.0, Qt 5.7.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 6.1.1 20160602)
PASS   : Test_NetConsoleSender::initTestCase()
PASS   : Test_NetConsoleSender::verifyMessage()
PASS   : Test_NetConsoleSender::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 102ms
********* Finished testing of Test_NetConsoleSender *********
********* Start testing of Test_NetConsoleReceiver *********
Config: Using QtTest library 5.7.0, Qt 5.7.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 6.1.1 20160602)
PASS   : Test_NetConsoleReceiver::initTestCase()
PASS   : Test_NetConsoleReceiver::verifyMessage()
PASS   : Test_NetConsoleReceiver::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 102ms
********* Finished testing of Test_NetConsoleReceiver *********
```

**Comment by alex-spataru** [comment]
Thanks for the information! I still have to work on the test cases (which are at a regrettable state right now :P), I get the same errors too.

Regarding the communication issues, could you put here the console output log? It is possible that the sockets module does not resolve the mDNS address before the robot watchdog expires (which in turn forces the sockets to perform another lookup). Could you try to input the robot's static IP to the [setCustomRobotAddress()](https://frc-utilities.github.io/documentation/libds/class_driver_station.html#a599c060b6993fd0a405fd5d9a45a3f14) function?

**Comment by alex-spataru** [comment]
@calcmogul I managed to reproduce your issue. I think it has something to do with the watchdog. I will keep you updated!

**Comment by alex-spataru** [comment]
I think I fixed the issue (hopefully). The lookup mechanism sometimes returns an empty string/IP. After the lookup finishes, the sockets module calls the [`setRobotAddress()`](https://github.com/FRC-Utilities/LibDS/blob/master/src/Core/Sockets.cpp#L400)  function to update the robot IP.

The problem was that the [`setRobotAddress()`](https://github.com/FRC-Utilities/LibDS/blob/master/src/Core/Sockets.cpp#L400) function did not check if the given IP was valid or not, effectively "overwriting" the valid robot IP that was found previously with an invalid IP address.

Can you check if the latest commit works for you too?

**Comment by calcmogul** [comment]
QDriverStation works now.

**Comment by alex-spataru** [comment]
Glad to hear it! Thanks for the report!
